#pragma once

namespace DefaultGame
{
	inline std::string ini =
	R"([/Script/FortniteGame.FortTextHotfixConfig]
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='Fortnite.FortAthenaMatchmakingWidget', Key='Message.CanMatchmakeSolo', NativeString='PLAY!', LocalizedStrings=(('ar','NEO PLAY!'),('en','NEO PLAY!'),('de','NEO PLAY!'),('es','Neonite'),('es-419','NEO PLAY!'),('fr','NEO PLAY!'),('it','NEO PLAY!'),('ja','NEO PLAY!'),('ko','NEO PLAY!'),('pl','NEO PLAY!'),('pt-BR','NEO PLAY!'),('ru','NEO PLAY!'),('tr','NEO PLAY!'),('zh-CN','NEO PLAY!'),('zh-Hant','NEO PLAY!')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='FriendNotFound', NativeString='{0} not found', LocalizedStrings=(('ar','Sorry, But we do not support friend'),('en','Sorry, But we do not support friend'),('de','Sorry, But we do not support friend'),('es','Neonite'),('es-419','Sorry, But we do not support friend'),('fr','Sorry, But we do not support friend'),('it','Sorry, But we do not support friend'),('ja','Sorry, But we do not support friend'),('ko','Sorry, But we do not support friend'),('pl','Sorry, But we do not support friend'),('pt-BR','Sorry, But we do not support friend'),('ru','Sorry, But we do not support friend'),('tr','Sorry, But we do not support friend'),('zh-CN','Sorry, But we do not support friend'),('zh-Hant','Sorry, But we do not support friend')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='FortUINotificationManager', Key='FriendToastFailureFmt', NativeString='{0} not found', LocalizedStrings=(('ar','Sorry, But we do not support friend'),('en','Sorry, But we do not support friend'),('de','Sorry, But we do not support friend'),('es','Neonite'),('es-419','Sorry, But we do not support friend'),('fr','Sorry, But we do not support friend'),('it','Sorry, But we do not support friend'),('ja','Sorry, But we do not support friend'),('ko','Sorry, But we do not support friend'),('pl','Sorry, But we do not support friend'),('pt-BR','Sorry, But we do not support friend'),('ru','Sorry, But we do not support friend'),('tr','Sorry, But we do not support friend'),('zh-CN','Sorry, But we do not support friend'),('zh-Hant','Sorry, But we do not support friend')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='AthenaSeasonItemDefinitionInternal', Key='ChapterTextFormat', NativeString='Chapter {0}', LocalizedStrings=(('ar','Chapter {0}, season 5'),('en','Chapter {0}, season 5'),('de','Chapter {0}, season 5'),('es','Neonite'),('es-419','Chapter {0}, season 5'),('fr','Chapter {0}, season 5'),('it','Chapter {0}, season 5'),('ja','Chapter {0}, season 5'),('ko','Chapter {0}, season 5'),('pl','Chapter {0}, season 5'),('pt-BR','Chapter {0}, season 5'),('ru','Chapter {0}, season 5'),('tr','Chapter {0}, season 5'),('zh-CN','Chapter {0}, season 5'),('zh-Hant','Chapter {0}, season 5')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='AthenaSeasonItemDefinitionInternal', Key='SeasonTextFormat', NativeString='Season {0}', LocalizedStrings=(('ar','Neonite'),('en','Neonite'),('de','Neonite'),('es','Neonite'),('es-419','Neonite'),('fr','Neonite'),('it','Neonite'),('ja','Neonite'),('ko','Neonite'),('pl','Neonite'),('pt-BR','Neonite'),('ru','Neonite'),('tr','Neonite'),('zh-CN','Neonite'),('zh-Hant','Neonite')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='Fort.Cosmetics', Key='CosmeticItemDescription_Season', NativeString='\nIntroduced in <SeasonText>{0}</>.', LocalizedStrings=(('ar',' '),('en',' '),('de',' '),('es',' '),('es-419',' '),('fr',' '),('it',' '),('ja',' '),('ko',' '),('pl',' '),('pt-BR',' '),('ru',' '),('tr',' '),('zh-CN',' '),('zh-Hant',' ')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='6A3D5DD84B30FD21AD83C7A7B07EB5E7', NativeString='Temporarily Disabled', LocalizedStrings=(('ar','Not Supported'),('en','Not Supported'),('de','Not Supported'),('es','Not Supported'),('es-419','Not Supported'),('fr','Not Supported'),('it','Not Supported'),('ja','Not Supported'),('ko','Not Supported'),('pl','Not Supported'),('pt-BR','Not Supported'),('ru','Not Supported'),('tr','Not Supported'),('zh-CN','Not Supported'),('zh-Hant','Not Supported')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='PartyContext', Key='BattleRoyaleInLobby', NativeString='Battle Royale - In Lobby', LocalizedStrings=(('ar','Neonite - In Lobby'),('en','Neonite - In Lobby'),('de','Neonite - In Lobby'),('es','Neonite - In Lobby'),('es-419','Neonite - In Lobby'),('fr','Neonite - In Lobby'),('it','Neonite - In Lobby'),('ja','Neonite - In Lobby'),('ko','Neonite - In Lobby'),('pl','Neonite - In Lobby'),('pt-BR','Neonite - In Lobby'),('ru','Neonite - In Lobby'),('tr','Neonite - In Lobby'),('zh-CN','Neonite - In Lobby'),('zh-Hant','Neonite - In Lobby')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='FortSettingValueDiscrete_Region', Key='RegionDisplayWithPing', NativeString='{RegionDisplayName} ({RegionPing}ms)', LocalizedStrings=(('ar','{RegionDisplayName} (1ms)'),('en','{RegionDisplayName} (1ms)'),('de','{RegionDisplayName} (1ms)'),('es','{RegionDisplayName} (1ms)'),('es-419','{RegionDisplayName} (1ms)'),('fr','{RegionDisplayName} (1ms)'),('it','{RegionDisplayName} (1ms)'),('ja','{RegionDisplayName} (1ms)'),('ko','{RegionDisplayName} (1ms)'),('pl','{RegionDisplayName} (1ms)'),('pt-BR','{RegionDisplayName} (1ms)'),('ru','{RegionDisplayName} (1ms)'),('tr','{RegionDisplayName} (1ms)'),('zh-CN','{RegionDisplayName} (1ms)'),('zh-Hant','{RegionDisplayName} (1ms)')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='FortTeamMemberPedestalNameplate', Key='NotReady', NativeString='Not Ready', LocalizedStrings=(('ar', 'Not Ready'),('en', 'Not Ready'),('de', 'Not Ready'),('es', 'Not Ready'),('es-419', 'Not Ready'),('fr', 'Not Ready'),('it', 'Not Ready'),('ja', 'Not Ready'),('ko', 'Not Ready'),('pl', 'Not Ready'),('pt-BR', 'Not Ready'),('ru', 'Not Ready'),('tr', 'Not Ready'),('zh-CN', 'Not Ready'),('zh-Hant', 'Not Ready')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='48DE963D48E224F0FA34B392EEBB04F3', NativeString='Drop In & Load Up', LocalizedStrings=(('ar', 'FreeCam'),('en', 'FreeCam'),('de', 'FreeCam'),('es', 'FreeCam'),('es-419', 'FreeCam'),('fr', 'FreeCam'),('it', 'FreeCam'),('ja', 'FreeCam'),('ko', 'FreeCam'),('pl', 'FreeCam'),('pt-BR', 'FreeCam'),('ru', 'FreeCam'),('tr', 'FreeCam'),('zh-CN', 'FreeCam'),('zh-Hant', 'FreeCam')))
)"

	R"(
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='1E2756A24E84E31CB6EFA19AABE6CEEE', NativeString='Pick a landing spot and search for gear.', LocalizedStrings=(('ar', 'Freecam around the map'),('en', 'Freecam around the map'),('de', 'Freecam around the map'),('es', 'Freecam around the map'),('es-419', 'Freecam around the map'),('fr', 'Freecam around the map'),('it', 'Freecam around the map'),('ja', 'Freecam around the map'),('ko', 'Freecam around the map'),('pl', 'Freecam around the map'),('pt-BR', 'Freecam around the map'),('ru', 'Freecam around the map'),('tr', 'Freecam around the map'),('zh-CN', 'Freecam around the map'),('zh-Hant', 'Freecam around the map')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='C21BFCC843ECBDD4244B80BC06CC68DC', NativeString='Last One Standing Wins', LocalizedStrings=(('ar', 'Credit'),('en', 'Credit'),('de', 'Credit'),('es', 'Credit'),('es-419', 'Credit'),('fr', 'Credit'),('it', 'Credit'),('ja', 'Credit'),('ko', 'Credit'),('pl', 'Credit'),('pt-BR', 'Credit'),('ru', 'Credit'),('tr', 'Credit'),('zh-CN', 'Credit'),('zh-Hant', 'Credit')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='3961708B410A75AE04191ABCAD93E9F0', NativeString='There can be only one winner.', LocalizedStrings=(('ar', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('en', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('de', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('es', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('es-419', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('fr', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('it', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('ja', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('ko', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('pl', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('pt-BR', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('ru', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('tr', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('zh-CN', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('zh-Hant', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='4EBD7A844DBAE6CA25581A80793B56F3', NativeString='There can be only one winner.', LocalizedStrings=(('ar', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('en', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('de', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('es', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('es-419', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('fr', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('it', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('ja', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('ko', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('pl', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('pt-BR', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('ru', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('tr', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('zh-CN', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('zh-Hant', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='900A843C489A158D9D7014B7688759B3', NativeString='There can be only one winner.', LocalizedStrings=(('ar', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('en', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('de', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('es', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('es-419', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('fr', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('it', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('ja', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('ko', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('pl', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('pt-BR', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('ru', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('tr', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('zh-CN', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('zh-Hant', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='C05138A24C74AAA74408CEBF86F9847B', NativeString='There can be only one winner.', LocalizedStrings=(('ar', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('en', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('de', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('es', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('es-419', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('fr', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('it', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('ja', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('ko', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('pl', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('pt-BR', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('ru', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('tr', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('zh-CN', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('zh-Hant', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='DBD8EB9C418D8B3F612D7091AB3132F5', NativeString='There can be only one winner.', LocalizedStrings=(('ar', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('en', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('de', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('es', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('es-419', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('fr', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('it', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('ja', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('ko', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('pl', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('pt-BR', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('ru', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('tr', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('zh-CN', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD'),('zh-Hant', 'Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='379AF5364909EC411609268F7630D591', NativeString='Stay Inside the Eye of the Storm', LocalizedStrings=(('ar', 'The Custom Experience'),('en', 'The Custom Experience'),('de', 'The Custom Experience'),('es', 'The Custom Experience'),('es-419', 'The Custom Experience'),('fr', 'The Custom Experience'),('it', 'The Custom Experience'),('ja', 'The Custom Experience'),('ko', 'The Custom Experience'),('pl', 'The Custom Experience'),('pt-BR', 'The Custom Experience'),('ru', 'The Custom Experience'),('tr', 'The Custom Experience'),('zh-CN', 'The Custom Experience'),('zh-Hant', 'The Custom Experience')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='3F18254E4FB808402F1D1AAF49B5442A', NativeString='Stay Inside the Eye of the Storm', LocalizedStrings=(('ar', 'The Custom Experience'),('en', 'The Custom Experience'),('de', 'The Custom Experience'),('es', 'The Custom Experience'),('es-419', 'The Custom Experience'),('fr', 'The Custom Experience'),('it', 'The Custom Experience'),('ja', 'The Custom Experience'),('ko', 'The Custom Experience'),('pl', 'The Custom Experience'),('pt-BR', 'The Custom Experience'),('ru', 'The Custom Experience'),('tr', 'The Custom Experience'),('zh-CN', 'The Custom Experience'),('zh-Hant', 'The Custom Experience')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='404A7F8F45CCEA3AC57992A9D25A2D4A', NativeString='Stay Inside the Eye of the Storm', LocalizedStrings=(('ar', 'The Custom Experience'),('en', 'The Custom Experience'),('de', 'The Custom Experience'),('es', 'The Custom Experience'),('es-419', 'The Custom Experience'),('fr', 'The Custom Experience'),('it', 'The Custom Experience'),('ja', 'The Custom Experience'),('ko', 'The Custom Experience'),('pl', 'The Custom Experience'),('pt-BR', 'The Custom Experience'),('ru', 'The Custom Experience'),('tr', 'The Custom Experience'),('zh-CN', 'The Custom Experience'),('zh-Hant', 'The Custom Experience')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='BD933A0A4D2108A6FF3D948E3CD2DBD4', NativeString='Stay Inside the Eye of the Storm', LocalizedStrings=(('ar', 'The Custom Experience'),('en', 'The Custom Experience'),('de', 'The Custom Experience'),('es', 'The Custom Experience'),('es-419', 'The Custom Experience'),('fr', 'The Custom Experience'),('it', 'The Custom Experience'),('ja', 'The Custom Experience'),('ko', 'The Custom Experience'),('pl', 'The Custom Experience'),('pt-BR', 'The Custom Experience'),('ru', 'The Custom Experience'),('tr', 'The Custom Experience'),('zh-CN', 'The Custom Experience'),('zh-Hant', 'The Custom Experience')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='C7E7507244A752D5FDD0259F1F775E83', NativeString='Stay Inside the Eye of the Storm', LocalizedStrings=(('ar', 'The Custom Experience'),('en', 'The Custom Experience'),('de', 'The Custom Experience'),('es', 'The Custom Experience'),('es-419', 'The Custom Experience'),('fr', 'The Custom Experience'),('it', 'The Custom Experience'),('ja', 'The Custom Experience'),('ko', 'The Custom Experience'),('pl', 'The Custom Experience'),('pt-BR', 'The Custom Experience'),('ru', 'The Custom Experience'),('tr', 'The Custom Experience'),('zh-CN', 'The Custom Experience'),('zh-Hant', 'The Custom Experience')))
)"

	R"(
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='BB7A860E4AC0955BAD6E3B99C32E1EEE', NativeString='Wired internet connections provide a faster and more stable connection than wireless.', LocalizedStrings=(('ar', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('en', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('de', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es-419', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('fr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('it', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ja', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ko', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pl', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pt-BR', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ru', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('tr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-CN', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-Hant', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='8D71E4BE45984C9ACCA63BAA1D238C55', NativeString='Explore quickly by building your own stairs and bridges.', LocalizedStrings=(('ar', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('en', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('de', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es-419', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('fr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('it', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ja', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ko', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pl', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pt-BR', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ru', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('tr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-CN', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-Hant', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='8582B6BF45BC20383D0F83B6AC522FE7', NativeString='As the eye of the storm shrinks, storm damage increases!', LocalizedStrings=(('ar', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('en', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('de', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es-419', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('fr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('it', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ja', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ko', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pl', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pt-BR', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ru', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('tr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-CN', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-Hant', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='F510BB8646A3364E481D8C87F8D38425', NativeString='Watch out! The storm closes in as the match progresses.', LocalizedStrings=(('ar', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('en', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('de', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es-419', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('fr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('it', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ja', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ko', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pl', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pt-BR', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ru', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('tr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-CN', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-Hant', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='9842E9A64552B80E54CBACB9DCECBA59', NativeString='The majority of items & gear can be found inside buildings.', LocalizedStrings=(('ar', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('en', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('de', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es-419', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('fr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('it', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ja', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ko', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pl', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pt-BR', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ru', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('tr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-CN', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-Hant', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='625C605044262E51C5167EB0DC5636D2', NativeString='Patch yourself up with Bandages. Use Med Kits to restore full health.', LocalizedStrings=(('ar', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('en', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('de', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es-419', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('fr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('it', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ja', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ko', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pl', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pt-BR', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ru', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('tr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-CN', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-Hant', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='534B47834656CD10DE988EA6A23A80DA', NativeString='Use Shield Potions to increase the total amount of damage you can take.', LocalizedStrings=(('ar', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('en', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('de', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es-419', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('fr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('it', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ja', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ko', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pl', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pt-BR', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ru', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('tr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-CN', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-Hant', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='5C5B5FB34DEF7ECD398304B329575A9F', NativeString='Shields will not protect you from falling damage, or the storm.', LocalizedStrings=(('ar', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('en', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('de', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es-419', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('fr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('it', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ja', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ko', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pl', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pt-BR', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ru', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('tr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-CN', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-Hant', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='236BEEC0428C7E07D0F7DD90C6B0BF49', NativeString='Open doors and looted treasure chests could mean other players are near.', LocalizedStrings=(('ar', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('en', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('de', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es-419', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('fr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('it', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ja', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ko', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pl', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pt-BR', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ru', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('tr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-CN', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-Hant', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2')))
)"

	R"(
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='B1DF088A4622B7C68D67CFBD8997E4D8', NativeString='Use the map to see where you are, and where the storm is headed.', LocalizedStrings=(('ar', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('en', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('de', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es-419', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('fr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('it', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ja', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ko', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pl', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pt-BR', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ru', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('tr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-CN', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-Hant', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='79A99D86421F77511F7A099F89E0DD75', NativeString='Headshots do significant damage. Aim for the head!', LocalizedStrings=(('ar', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('en', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('de', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es-419', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('fr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('it', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ja', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ko', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pl', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pt-BR', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ru', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('tr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-CN', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-Hant', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='388330414546BA61F46AC0BC99E0BD75', NativeString='Shotguns, SMGs, and Pistols are effective at close range.', LocalizedStrings=(('ar', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('en', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('de', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('es-419', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('fr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('it', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ja', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ko', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pl', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('pt-BR', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('ru', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('tr', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-CN', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2'),('zh-Hant', 'Fun Fact: Neonite++ is a recreation of the old Neonite V2')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='997807D8415CCC8E255C3090853CB425', NativeString='Assault Rifles are effective at medium range.', LocalizedStrings=(('ar', 'Press the ` key on your keyboard to open the console'),('en', 'Press the ` key on your keyboard to open the console'),('de', 'Press the ` key on your keyboard to open the console'),('es', 'Press the ` key on your keyboard to open the console'),('es-419', 'Press the ` key on your keyboard to open the console'),('fr', 'Press the ` key on your keyboard to open the console'),('it', 'Press the ` key on your keyboard to open the console'),('ja', 'Press the ` key on your keyboard to open the console'),('ko', 'Press the ` key on your keyboard to open the console'),('pl', 'Press the ` key on your keyboard to open the console'),('pt-BR', 'Press the ` key on your keyboard to open the console'),('ru', 'Press the ` key on your keyboard to open the console'),('tr', 'Press the ` key on your keyboard to open the console'),('zh-CN', 'Press the ` key on your keyboard to open the console'),('zh-Hant', 'Press the ` key on your keyboard to open the console')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='4248E0904591CC6FF8A6F4AAC5EBC73E', NativeString='Sniper Rifles are effective at long range.', LocalizedStrings=(('ar', 'Press the ` key on your keyboard to open the console'),('en', 'Press the ` key on your keyboard to open the console'),('de', 'Press the ` key on your keyboard to open the console'),('es', 'Press the ` key on your keyboard to open the console'),('es-419', 'Press the ` key on your keyboard to open the console'),('fr', 'Press the ` key on your keyboard to open the console'),('it', 'Press the ` key on your keyboard to open the console'),('ja', 'Press the ` key on your keyboard to open the console'),('ko', 'Press the ` key on your keyboard to open the console'),('pl', 'Press the ` key on your keyboard to open the console'),('pt-BR', 'Press the ` key on your keyboard to open the console'),('ru', 'Press the ` key on your keyboard to open the console'),('tr', 'Press the ` key on your keyboard to open the console'),('zh-CN', 'Press the ` key on your keyboard to open the console'),('zh-Hant', 'Press the ` key on your keyboard to open the console')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='CC53D6BD47A4C450DC66B2BEA7D7C1D1', NativeString='Place traps in places where other players won’t see them.', LocalizedStrings=(('ar', 'Press the ` key on your keyboard to open the console'),('en', 'Press the ` key on your keyboard to open the console'),('de', 'Press the ` key on your keyboard to open the console'),('es', 'Press the ` key on your keyboard to open the console'),('es-419', 'Press the ` key on your keyboard to open the console'),('fr', 'Press the ` key on your keyboard to open the console'),('it', 'Press the ` key on your keyboard to open the console'),('ja', 'Press the ` key on your keyboard to open the console'),('ko', 'Press the ` key on your keyboard to open the console'),('pl', 'Press the ` key on your keyboard to open the console'),('pt-BR', 'Press the ` key on your keyboard to open the console'),('ru', 'Press the ` key on your keyboard to open the console'),('tr', 'Press the ` key on your keyboard to open the console'),('zh-CN', 'Press the ` key on your keyboard to open the console'),('zh-Hant', 'Press the ` key on your keyboard to open the console')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='1E41BAE945413302F19C53AD797BEBCE', NativeString='Listen carefully! You may hear an approaching player’s footsteps.', LocalizedStrings=(('ar', 'Press the ` key on your keyboard to open the console'),('en', 'Press the ` key on your keyboard to open the console'),('de', 'Press the ` key on your keyboard to open the console'),('es', 'Press the ` key on your keyboard to open the console'),('es-419', 'Press the ` key on your keyboard to open the console'),('fr', 'Press the ` key on your keyboard to open the console'),('it', 'Press the ` key on your keyboard to open the console'),('ja', 'Press the ` key on your keyboard to open the console'),('ko', 'Press the ` key on your keyboard to open the console'),('pl', 'Press the ` key on your keyboard to open the console'),('pt-BR', 'Press the ` key on your keyboard to open the console'),('ru', 'Press the ` key on your keyboard to open the console'),('tr', 'Press the ` key on your keyboard to open the console'),('zh-CN', 'Press the ` key on your keyboard to open the console'),('zh-Hant', 'Press the ` key on your keyboard to open the console')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='282585074F9C7E04391A1B9E4C93A262', NativeString='Making too much noise can alert others to your position.', LocalizedStrings=(('ar', 'Press the ` key on your keyboard to open the console'),('en', 'Press the ` key on your keyboard to open the console'),('de', 'Press the ` key on your keyboard to open the console'),('es', 'Press the ` key on your keyboard to open the console'),('es-419', 'Press the ` key on your keyboard to open the console'),('fr', 'Press the ` key on your keyboard to open the console'),('it', 'Press the ` key on your keyboard to open the console'),('ja', 'Press the ` key on your keyboard to open the console'),('ko', 'Press the ` key on your keyboard to open the console'),('pl', 'Press the ` key on your keyboard to open the console'),('pt-BR', 'Press the ` key on your keyboard to open the console'),('ru', 'Press the ` key on your keyboard to open the console'),('tr', 'Press the ` key on your keyboard to open the console'),('zh-CN', 'Press the ` key on your keyboard to open the console'),('zh-Hant', 'Press the ` key on your keyboard to open the console')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='1F04B7554407DED999C4D48658A1001D', NativeString='Moving while shooting will decrease weapon accuracy.', LocalizedStrings=(('ar', 'Press the ` key on your keyboard to open the console'),('en', 'Press the ` key on your keyboard to open the console'),('de', 'Press the ` key on your keyboard to open the console'),('es', 'Press the ` key on your keyboard to open the console'),('es-419', 'Press the ` key on your keyboard to open the console'),('fr', 'Press the ` key on your keyboard to open the console'),('it', 'Press the ` key on your keyboard to open the console'),('ja', 'Press the ` key on your keyboard to open the console'),('ko', 'Press the ` key on your keyboard to open the console'),('pl', 'Press the ` key on your keyboard to open the console'),('pt-BR', 'Press the ` key on your keyboard to open the console'),('ru', 'Press the ` key on your keyboard to open the console'),('tr', 'Press the ` key on your keyboard to open the console'),('zh-CN', 'Press the ` key on your keyboard to open the console'),('zh-Hant', 'Press the ` key on your keyboard to open the console')))
)"

	R"(
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='00099F2E4B0E8E825E6BF2B29AB52694', NativeString='Use crouch to reduce your profile, or to hide behind smaller objects.', LocalizedStrings=(('ar', 'Press the ` key on your keyboard to open the console'),('en', 'Press the ` key on your keyboard to open the console'),('de', 'Press the ` key on your keyboard to open the console'),('es', 'Press the ` key on your keyboard to open the console'),('es-419', 'Press the ` key on your keyboard to open the console'),('fr', 'Press the ` key on your keyboard to open the console'),('it', 'Press the ` key on your keyboard to open the console'),('ja', 'Press the ` key on your keyboard to open the console'),('ko', 'Press the ` key on your keyboard to open the console'),('pl', 'Press the ` key on your keyboard to open the console'),('pt-BR', 'Press the ` key on your keyboard to open the console'),('ru', 'Press the ` key on your keyboard to open the console'),('tr', 'Press the ` key on your keyboard to open the console'),('zh-CN', 'Press the ` key on your keyboard to open the console'),('zh-Hant', 'Press the ` key on your keyboard to open the console')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='442C492A4329BA3B8F46B4AF6A372ECD', NativeString='Doors stay open until closed. Hide your tracks by closing doors.', LocalizedStrings=(('ar', 'Press the ` key on your keyboard to open the console'),('en', 'Press the ` key on your keyboard to open the console'),('de', 'Press the ` key on your keyboard to open the console'),('es', 'Press the ` key on your keyboard to open the console'),('es-419', 'Press the ` key on your keyboard to open the console'),('fr', 'Press the ` key on your keyboard to open the console'),('it', 'Press the ` key on your keyboard to open the console'),('ja', 'Press the ` key on your keyboard to open the console'),('ko', 'Press the ` key on your keyboard to open the console'),('pl', 'Press the ` key on your keyboard to open the console'),('pt-BR', 'Press the ` key on your keyboard to open the console'),('ru', 'Press the ` key on your keyboard to open the console'),('tr', 'Press the ` key on your keyboard to open the console'),('zh-CN', 'Press the ` key on your keyboard to open the console'),('zh-Hant', 'Press the ` key on your keyboard to open the console')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='6F5CB8E648CD715B98164FB62D5017C7', NativeString='Finding an open door means someone else has already been there.', LocalizedStrings=(('ar', 'Press the ` key on your keyboard to open the console'),('en', 'Press the ` key on your keyboard to open the console'),('de', 'Press the ` key on your keyboard to open the console'),('es', 'Press the ` key on your keyboard to open the console'),('es-419', 'Press the ` key on your keyboard to open the console'),('fr', 'Press the ` key on your keyboard to open the console'),('it', 'Press the ` key on your keyboard to open the console'),('ja', 'Press the ` key on your keyboard to open the console'),('ko', 'Press the ` key on your keyboard to open the console'),('pl', 'Press the ` key on your keyboard to open the console'),('pt-BR', 'Press the ` key on your keyboard to open the console'),('ru', 'Press the ` key on your keyboard to open the console'),('tr', 'Press the ` key on your keyboard to open the console'),('zh-CN', 'Press the ` key on your keyboard to open the console'),('zh-Hant', 'Press the ` key on your keyboard to open the console')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='787D94CE4ACF92343A883BA2917A4AEF', NativeString='Inventory space is limited - choose your loadout wisely.', LocalizedStrings=(('ar', 'Press the ` key on your keyboard to open the console'),('en', 'Press the ` key on your keyboard to open the console'),('de', 'Press the ` key on your keyboard to open the console'),('es', 'Press the ` key on your keyboard to open the console'),('es-419', 'Press the ` key on your keyboard to open the console'),('fr', 'Press the ` key on your keyboard to open the console'),('it', 'Press the ` key on your keyboard to open the console'),('ja', 'Press the ` key on your keyboard to open the console'),('ko', 'Press the ` key on your keyboard to open the console'),('pl', 'Press the ` key on your keyboard to open the console'),('pt-BR', 'Press the ` key on your keyboard to open the console'),('ru', 'Press the ` key on your keyboard to open the console'),('tr', 'Press the ` key on your keyboard to open the console'),('zh-CN', 'Press the ` key on your keyboard to open the console'),('zh-Hant', 'Press the ` key on your keyboard to open the console')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='674CEA324A6FEC0921BB59BCA386BA6E', NativeString='When your inventory is full, picking up an item will swap it with what is currently equipped.', LocalizedStrings=(('ar', 'Press the ` key on your keyboard to open the console'),('en', 'Press the ` key on your keyboard to open the console'),('de', 'Press the ` key on your keyboard to open the console'),('es', 'Press the ` key on your keyboard to open the console'),('es-419', 'Press the ` key on your keyboard to open the console'),('fr', 'Press the ` key on your keyboard to open the console'),('it', 'Press the ` key on your keyboard to open the console'),('ja', 'Press the ` key on your keyboard to open the console'),('ko', 'Press the ` key on your keyboard to open the console'),('pl', 'Press the ` key on your keyboard to open the console'),('pt-BR', 'Press the ` key on your keyboard to open the console'),('ru', 'Press the ` key on your keyboard to open the console'),('tr', 'Press the ` key on your keyboard to open the console'),('zh-CN', 'Press the ` key on your keyboard to open the console'),('zh-Hant', 'Press the ` key on your keyboard to open the console')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='9842663F4D5641478260D9AB9F07E65B', NativeString='Ammo, building resources, and traps do not take inventory space. Pick up as many as you like!', LocalizedStrings=(('ar', 'Press the ` key on your keyboard to open the console'),('en', 'Press the ` key on your keyboard to open the console'),('de', 'Press the ` key on your keyboard to open the console'),('es', 'Press the ` key on your keyboard to open the console'),('es-419', 'Press the ` key on your keyboard to open the console'),('fr', 'Press the ` key on your keyboard to open the console'),('it', 'Press the ` key on your keyboard to open the console'),('ja', 'Press the ` key on your keyboard to open the console'),('ko', 'Press the ` key on your keyboard to open the console'),('pl', 'Press the ` key on your keyboard to open the console'),('pt-BR', 'Press the ` key on your keyboard to open the console'),('ru', 'Press the ` key on your keyboard to open the console'),('tr', 'Press the ` key on your keyboard to open the console'),('zh-CN', 'Press the ` key on your keyboard to open the console'),('zh-Hant', 'Press the ` key on your keyboard to open the console')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='E4EFCDE041C290380ABF3095D5F79BB5', NativeString='You can change which slots your items are assigned to in the inventory screen.', LocalizedStrings=(('ar', 'Press the ` key on your keyboard to open the console'),('en', 'Press the ` key on your keyboard to open the console'),('de', 'Press the ` key on your keyboard to open the console'),('es', 'Press the ` key on your keyboard to open the console'),('es-419', 'Press the ` key on your keyboard to open the console'),('fr', 'Press the ` key on your keyboard to open the console'),('it', 'Press the ` key on your keyboard to open the console'),('ja', 'Press the ` key on your keyboard to open the console'),('ko', 'Press the ` key on your keyboard to open the console'),('pl', 'Press the ` key on your keyboard to open the console'),('pt-BR', 'Press the ` key on your keyboard to open the console'),('ru', 'Press the ` key on your keyboard to open the console'),('tr', 'Press the ` key on your keyboard to open the console'),('zh-CN', 'Press the ` key on your keyboard to open the console'),('zh-Hant', 'Press the ` key on your keyboard to open the console')))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace='', Key='7C2FC1C24FC3A13DD408AEA3F5E9C4AC', NativeString='While skydiving, hold forward to get to your destination faster.', LocalizedStrings=(('ar', 'Press the ` key on your keyboard to open the console'),('en', 'Press the ` key on your keyboard to open the console'),('de', 'Press the ` key on your keyboard to open the console'),('es', 'Press the ` key on your keyboard to open the console'),('es-419', 'Press the ` key on your keyboard to open the console'),('fr', 'Press the ` key on your keyboard to open the console'),('it', 'Press the ` key on your keyboard to open the console'),('ja', 'Press the ` key on your keyboard to open the console'),('ko', 'Press the ` key on your keyboard to open the console'),('pl', 'Press the ` key on your keyboard to open the console'),('pt-BR', 'Press the ` key on your keyboard to open the console'),('ru', 'Press the ` key on your keyboard to open the console'),('tr', 'Press the ` key on your keyboard to open the console'),('zh-CN', 'Press the ` key on your keyboard to open the console'),('zh-Hant', 'Press the ` key on your keyboard to open the console')))
)"

	R"(
[/Script/FortniteGame.FortGameInstance]
bBattleRoyaleMatchmakingEnabled=true
bCreativeModeProfileEnabled=true
!FrontEndPlaylistData=ClearArray
+FrontEndPlaylistData=(PlaylistName=Playlist_DefaultDuo, PlaylistAccess=(bEnabled=false))
+FrontEndPlaylistData=(PlaylistName=Playlist_DefaultSquad, PlaylistAccess=(bEnabled=false))
+FrontEndPlaylistData=(PlaylistName=Playlist_Respawn_24, PlaylistAccess=(bEnabled=false))
+FrontEndPlaylistData=(PlaylistName=Playlist_Playground, PlaylistAccess=(bEnabled=false))
+FrontEndPlaylistData=(PlaylistName=Playlist_PlaygroundV2, PlaylistAccess=(bEnabled=false, bForcePlaylistOff=true))
+FrontEndPlaylistData=(PlaylistName=Playlist_ShowdownAlt_Solo, PlaylistAccess=(bEnabled=false, bForcePlaylistOff=true))
+FrontEndPlaylistData=(PlaylistName=Playlist_ShowdownAlt_Duos, PlaylistAccess=(bEnabled=false, bForcePlaylistOff=true))
+FrontEndPlaylistData=(PlaylistName=Playlist_ShowdownAlt_Trios, PlaylistAccess=(bEnabled=false, bForcePlaylistOff=true))
+FrontEndPlaylistData=(PlaylistName=Playlist_ShowdownTournament_Solo, PlaylistAccess=(bEnabled=false, bForcePlaylistOff=true))
+FrontEndPlaylistData=(PlaylistName=Playlist_ShowdownTournament_Duos , PlaylistAccess=(bEnabled=false, bForcePlaylistOff=true))
+FrontEndPlaylistData=(PlaylistName=Playlist_ShowdownTournament_Trios, PlaylistAccess=(bEnabled=false, bForcePlaylistOff=true))
+FrontEndPlaylistData=(PlaylistName=Playlist_DefaultSolo, PlaylistAccess=(bEnabled=true, bIsDefaultPlaylist=true, bDisplayAsLimitedTime=false, DisplayPriority=0, CategoryIndex=0))
+FrontEndPlaylistData=(PlaylistName=Playlist_Papaya, PlaylistAccess=(bEnabled=false, bIsDefaultPlaylist=true, bDisplayAsLimitedTime=false, DisplayPriority=0, CategoryIndex=1))

[/Script/FortniteGame.FortGlobals]
bAthenaLeaderboardFrontEndEnabled=false
bAthenaStatsFrontendEnabled=false
bGlobalLeaderboardsFrontEndEnabled=false
SubGameAccess=(SubGame=Campaign,AccessStatus=OpenAccess,MatchmakingStatus=Enabled)
+SubGameAccess=(SubGame=Athena,AccessStatus=OpenAccess,MatchmakingStatus=Enabled)
+SubGameAccess=(SubGame=Campaign,AccessStatus=OpenAccess,MatchmakingStatus=Enabled)
bUploadAthenaStats=false
bUploadAthenaStatsV2=false

[/Script/FortniteGame.FortMatchmakingV2]
bCustomKeyEnabled=false
)";

	inline std::string name = "DefaultGame.ini";
	inline std::string sha1 = "5111adb2ec33af32bcf7227618f60004ff48893a";
	inline std::string sha256 = "a527493a47a49d2e84db88a9b4b9196bf2718c860010b9d5a5d25a9d59f2e3b2";
}
